version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "blog-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-187zw6rgxtqrr"
s3_prefix = "blog-api"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
